### ISSUE TITLE
support add this repo as component (IDFGH-7672)

### ISSUE THREAD

**Issue by phatpaul** [espressif/idf-flash-vendor-patches#1]
Split this repo into a component and an example which includes it as a submodule.
That way I don't have to copy/paste the code into my project, I can easily add this to my project as a submodule in /components.

**Comment by igrr** [comment]
@phatpaul We might need to add more components to this project (although we hope we don't have to...) so we would prefer to keep the existing structure.

I think you can still add this as a submodule (not into the `components` directory), then set EXTRA_COMPONENT_DIRS in your project to point to the component location:
```cmake
set(EXTRA_COMPONENT_DIRS ${CMAKE_CURRENT_LIST_DIR}/../patches/idf-flash-vendor-patches/components/idf-flash-vendor-patches)
```

Another option, in IDF v4.2.2 and later, it is also possible to install this component using the [IDF component manager](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/tools/idf-component-manager.html). For example, by adding an `idf_component.yml` file to one of your project's components, with the following contents:
```
dependencies:
  idf-flash-vendor-patches:
    path: components/idf-flash-vendor-patches
    git: https://github.com/espressif/idf-flash-vendor-patches.git
```
